### ISSUE TITLE
reordering models has caused major problems in the database

### ISSUE THREAD

**Issue by kkellydesign** [caktus/django-treenav#42] opened 2015-03-12 20:41 UTC
Hello, 
I have a strange problem. I was reordering the navigation on a client's site and the main list suddenly completely rearranged itself. Clearing the cache and refreshing hrefs isn't helping, and I tried to do a cache.clear from the shell, and nothing seems to be working. You can see the problem here: 

![screen shot 2015-03-12 at 4 29 11 pm](https://cloud.githubusercontent.com/assets/202590/6627492/f2c49c96-c8d4-11e4-8afb-784e3897735c.png)

When you click on "skin type", you can see that the parent is actually "tan safely", not "main-nav"

![screen shot 2015-03-12 at 4 38 54 pm](https://cloud.githubusercontent.com/assets/202590/6627678/4ea2a278-c8d6-11e4-8a2d-7373773223b2.png)

This is the *correct* ordering, but that's not what is showing up in the Menu Items list or the navigation of the site. This is the second time this has happened to me on different sites in the past two weeks, and it seems like a pretty major issue, so I'm wondering if I'm doing something wrong in my site configuration. Any ideas? 

Thanks, 

Kasey

**Comment by jMyles** [comment] 2015-08-28 21:52
This ticket seems to describe two issues:

* Issue A: MenuItems are listed in the admin in a way that does not correspond to their Parent (ie, 'skin type' is listed as if its parent were 'main-nav', when it is in fact 'tan-safety')
* Issue B: MenuItems are listed in the admin and displayed in the site navigation in a way that does not order them by the "order" attribute.

In any example (provided to me by @kkellydesign), I am able to easily reproduce Issue B, but not Issue A.

A Menu, populated with MenuItems, appears this way in the admin:

![selection_002](https://cloud.githubusercontent.com/assets/311973/9557830/1a8d858c-4dad-11e5-9259-64e81a7bb70c.png)

Notice that "test" appears above "Cristal" even though their order attributes are opposite.  The same is true of "Photo_Gallery" which appears above "Regalia" and "Majestica" despite having a higher order.

However, the same menu appears in the site nav in a completely different, but also incorrect order:

![selection_003](https://cloud.githubusercontent.com/assets/311973/9557840/3af2ae56-4dad-11e5-870c-43c43f18c688.png)

As you can see, the order here is also incorrect, but with no apparent pattern compared to the admin (for the record, it's "1, 2, 3, 5, 8, 4, 6, 7, 9").

This may be explained in part by the fact that django-treenav has a Meta class for the MenuItem model which uses "('lft', 'tree_id')" as the ordering directive, but ('order',) as the "order_insertion_by" directive.  I've 'never seen "order_insertion_by" before, but a google search yields, among other less interesting leads, this question on StackOverflow:

http://stackoverflow.com/questions/27874094/bug-in-django-mpttmeta-order-insertion-by-causes-nodes-to-report-incorrect-desce

However, the app in question is using a version of django-mptt with the fix (noted in an SO answer above) already applied.

As expected, the value of `self._meta.ordering` for a MenuItem instance is ('lft', 'tree_id').

**Comment by jMyles** [comment] 2015-08-28 21:54
It is not immediately obvious to me where the 'lft' attribute is defined.

**Comment by jMyles** [comment] 2015-08-28 22:09
I'm not sure if this insight is useful or not, but if I simply add "(lft: {{item.node.lft}})" to the template in order to get it to show the value of 'lft' for each MenuItem, I get this:

![selection_004](https://cloud.githubusercontent.com/assets/311973/9558107/dc2a38d2-4daf-11e5-9d63-3afd3670eb93.png)

...but it's still not clear to me where that value is set or, for that matter, why.

**Comment by jMyles** [comment] 2015-08-28 22:14
'lft' is a PositiveIntegerField in this migration:

https://github.com/caktus/django-treenav/blob/56a272c51477b2b8483c6a5603fdb74fb859c015/treenav/migrations/0001_initial.py#L23

**Comment by mlavin** [comment] 2015-08-28 23:41
`lft`, `rght`, `tree_id`, and `level` are the fields added by and managed MPTT for the tree structure.

**Comment by jMyles** [comment] 2015-08-28 23:47
Hey Mark.  Good to see you man.  :-)

Yeah, I realize that now, and, in the comment above, I indicated the lines where the *fields* are added.  I don't, however, see where the value is assigned.

I don't find this segment particularly cognizable or pythonic; it seems to be largely an exercise in adding obscurity.  I realize that its purpose is to "treeify" existing models; perhaps it can be turned into model-swapping logic with the new swappable models API.  

In any case, my immediate desire is to understand why this ordering issue persists and how to apply at least a near-term fix that will be forward-compatible.

**Comment by mlavin** [comment] 2015-08-29 00:57
There have been a number of issues related to ordering #2/#7 which were related to  bug in MPTT and reproduced via 684c07083f6fc6608ba472bc1cd63a07204a5f94 and #17 which was never reproducible. This project in general needs a bit of love and attention but I don't expect any of these ordering problems can be addressed without some failing test cases.

**Comment by vkurup** [comment] 2015-09-02 15:27
A workaround for this has been provided by @jMyles and is in the [0.9.2 Release](https://pypi.python.org/pypi/django-treenav/0.9.2).

May be worth keeping this issue open, at least to remind us to add documentation to use the new 'rebuild tree' command if ordering issues arise.

**Comment by benred42** [comment] 2015-09-22 15:18
I did a little looking around and there are a few people who have mentioned that having list editable fields in the admin can lead to tree structure issues:
https://github.com/django-mptt/django-mptt/issues/233
http://stackoverflow.com/questions/20578704/ordering-mptt-tree-using-a-field

Don't know if that's the case here, but the label field for menu items is list editable.

**Comment by kkellydesign** [comment] 2015-09-22 15:20
hm. I also get an error when I try to delete an item from the list view –
that could be related as well.

On Tue, Sep 22, 2015 at 11:18 AM, Benjamin Phillips <
notifications@github.com> wrote:

> I did a little looking around and there are a few people who have
> mentioned that having list editable fields in the admin can lead to tree
> structure issues:
> django-mptt/django-mptt#233
> <https://github.com/django-mptt/django-mptt/issues/233>
>
> http://stackoverflow.com/questions/20578704/ordering-mptt-tree-using-a-field
>
> Don't know if that's the case here, but the label field for menu items is
> list editable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caktus/django-treenav/issues/42#issuecomment-142321334>
> .
>



-- 
Kasey Kelly
kellycreativetech.com
330.351.9352

**Comment by jMyles** [comment] 2015-09-22 15:26
Kasey,

What is the error?

**Comment by kkellydesign** [comment] 2015-09-22 16:32
Sorry, I should've probably filed another ticket. I'm pretty sure it's
unrelated to any of your work, Justin. It's easy to recreate though:

* In the list view (/admin/treenav/menuitem/), hit a checkbox and then
choose "delete selected menu items", and confirm on the next screen.
* error message: 'MenuItemManager' object has no attribute
'delay_mptt_updates'

On Tue, Sep 22, 2015 at 11:26 AM, Justin Holmes <notifications@github.com>
wrote:

> Kasey,
>
> What is the error?
>
> On Tue, Sep 22, 2015 at 11:20 AM, Kasey Kelly <notifications@github.com>
> wrote:
>
> > hm. I also get an error when I try to delete an item from the list view –
> > that could be related as well.
> >
> > On Tue, Sep 22, 2015 at 11:18 AM, Benjamin Phillips <
> > notifications@github.com> wrote:
> >
> > > I did a little looking around and there are a few people who have
> > > mentioned that having list editable fields in the admin can lead to
> tree
> > > structure issues:
> > > django-mptt/django-mptt#233
> > > <https://github.com/django-mptt/django-mptt/issues/233>
> > >
> > >
> >
> http://stackoverflow.com/questions/20578704/ordering-mptt-tree-using-a-field
> > >
> > > Don't know if that's the case here, but the label field for menu items
> is
> > > list editable.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/caktus/django-treenav/issues/42#issuecomment-142321334>
> > > .
> > >
> >
> >
> >
> > --
> > Kasey Kelly
> > kellycreativetech.com
> > 330.351.9352
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/caktus/django-treenav/issues/42#issuecomment-142321810>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caktus/django-treenav/issues/42#issuecomment-142323594>
> .
>



-- 
Kasey Kelly
kellycreativetech.com
330.351.9352

**Comment by benred42** [comment] 2015-09-22 16:54
That could be due to the fact that MenuItemManager inherits from Django's models.Manager instead of from the custom MPTT TreeManager.  It looks like the MenuItem model uses MenuItemManager as its default manager and the TreeManager for tree-specific functions?

**Comment by benred42** [comment] 2015-09-30 18:20
We've put a fix in place that looks to have dealt with this issue so I'm going to go ahead and close it, but please let us know if you see it reappear at any point.

**Closed by benred42** 2015-09-30 18:20 UTC
